"""Prometheus custom metrics для Phase 00.6 staging stack.

Метрики делятся на три семейства:

* **llm_*** — LLM provider observability (requests, tokens, cost, latency,
  health). Labels: provider, model, status, cell_id (где уместно).
* **task_*** — task pipeline observability (duration, total, queue_depth).
  Labels: role_key, outcome, cell_id.
* **billing_*** — RU-currency cost ledger (delegates к llm_cost_rub).

Все метрики регистрируются один раз через `register_default_metrics()`
которая идемпотентна (guard via prometheus_client REGISTRY presence-check).
Per-callsite instrumentation в orchestrator/router_service/cost_recorder
ландит в Wave-1 hardening — Phase 00.6 ships ТОЛЬКО registration + /metrics
endpoint (см. AUDIT-W1-2 pin block).

Wired в `src/main.py`:
    from src._shared.observability import register_default_metrics
    from prometheus_client import make_asgi_app
    register_default_metrics()
    app.mount("/metrics", make_asgi_app())
"""

from __future__ import annotations

from prometheus_client import REGISTRY, Counter, Gauge, Histogram

__all__ = [
    "LLM_COST_RUB",
    "LLM_LATENCY",
    "LLM_PROVIDER_HEALTH",
    "LLM_REQUEST_TOTAL",
    "LLM_TOKENS_INPUT",
    "LLM_TOKENS_OUTPUT",
    "TASK_DURATION",
    "TASK_QUEUE_DEPTH",
    "TASK_TOTAL",
    "register_default_metrics",
]


# ── LLM family ──────────────────────────────────────────────────────────

LLM_REQUEST_TOTAL = Counter(
    "llm_request_total",
    "Total LLM requests issued through the gateway, partitioned by outcome.",
    ["provider", "model", "status"],
)

LLM_TOKENS_INPUT = Counter(
    "llm_tokens_input_total",
    "Cumulative input tokens consumed by provider/model.",
    ["provider", "model"],
)

LLM_TOKENS_OUTPUT = Counter(
    "llm_tokens_output_total",
    "Cumulative output tokens generated by provider/model.",
    ["provider", "model"],
)

LLM_COST_RUB = Counter(
    "llm_cost_rub_total",
    "Cumulative billable cost в RUB per provider/model/cell. RU-currency "
    "settlement per ADR-018 amendment 2026-05-19; `cost_rub = cost_usd × "
    "fx_rate_usd_to_rub`.",
    ["provider", "model", "cell_id"],
)

LLM_LATENCY = Histogram(
    "llm_request_latency_seconds",
    "End-to-end latency of an LLM gateway call (request → final token).",
    ["provider", "model"],
    # SLO targets per AC8 — coarse buckets ниже 1s + finer above 5s where
    # demo-flow p95 lives (Wave-0 expects ~10-30s per LLM call).
    buckets=(0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 30.0, 45.0, 60.0, 90.0, 120.0),
)

LLM_PROVIDER_HEALTH = Gauge(
    "llm_provider_health",
    "Circuit-breaker state per provider: 1=closed (healthy), "
    "0.5=half-open (probing), 0=open (down). Set by "
    "llm_gateway.circuit_breaker.ProviderCircuit on state transitions.",
    ["provider"],
)


# ── Task family ─────────────────────────────────────────────────────────

TASK_DURATION = Histogram(
    "task_duration_seconds",
    "End-to-end task duration from queued → terminal (succeeded/failed/"
    "cancelled). Labelled by role_key (coordinator/researcher/writer/analyst) "
    "and outcome.",
    ["role_key", "outcome"],
    buckets=(0.5, 1.0, 5.0, 10.0, 30.0, 60.0, 90.0, 120.0, 180.0, 300.0, 600.0),
)

TASK_TOTAL = Counter(
    "task_total",
    "Total tasks executed по cells, partitioned by outcome (succeeded/"
    "failed/cancelled/budget_exceeded).",
    ["cell_id", "outcome"],
)

TASK_QUEUE_DEPTH = Gauge(
    "task_queue_depth",
    "Current count pending tasks (queued + running) per cell. Updated by "
    "orchestrator on task state-transitions.",
    ["cell_id"],
)


def register_default_metrics() -> None:
    """Force-import + sanity-check Prometheus metric registration.

    Idempotent. The 9 module-level Counter/Gauge/Histogram constructors above
    auto-register с the global `prometheus_client.REGISTRY` at import-time
    (Python module import is cached, so re-calling this function does NOT
    re-register — the touch is just to defeat lazy-import pruning).

    The sanity check compares stripped base-names: prometheus_client v0.20+
    drops the `_total` suffix from Counter `m.name` while keeping it in
    sample names (`llm_request_total` Counter → base name `llm_request` +
    sample `llm_request_total`). We compare against base names.
    """
    expected_bases = {
        # Counter base names (without _total suffix):
        "llm_request",
        "llm_tokens_input",
        "llm_tokens_output",
        "llm_cost_rub",
        "task",
        # Histogram + Gauge — names taken verbatim:
        "llm_request_latency_seconds",
        "llm_provider_health",
        "task_duration_seconds",
        "task_queue_depth",
    }
    present = {m.name for m in REGISTRY.collect()}
    missing = expected_bases - present
    if missing:
        raise RuntimeError(
            f"Phase 00.6 metrics registration drift — missing base names: "
            f"{sorted(missing)}. Check import order: src._shared.observability"
            f".metrics must be importable from src.main lifespan."
        )
