/**
 * memory endpoints — schemas pinned to the live backend
 * (backend/src/memory/routers/memory.py + schemas.py, ADR-011 Wave-1).
 *
 * Cell scope is implicit (RLS tenant context via `get_current_cell_id`,
 * Wave-0 single-cell-per-user) — no `cell_id` path param on the cell-memory
 * endpoints. Role-memory endpoints take an explicit `agent_id` path param.
 * Search uses the `q` query param (not `query`) per the router signature.
 */
import { z } from "zod";
import { apiFetch } from "./client";

/** Manual-create kinds — a subset of the DB CHECK (`conversation_summary` is
 * system-generated by the summarizer, never through the manual endpoints). */
export const CELL_MEMORY_KINDS = ["fact", "note", "glossary"] as const;
export type CellMemoryKind = (typeof CELL_MEMORY_KINDS)[number];

export const ROLE_MEMORY_KINDS = ["preference", "style", "process", "fact", "note"] as const;
export type RoleMemoryKind = (typeof ROLE_MEMORY_KINDS)[number];

/** `source` DB CHECK is `'manual' | 'filter_agent' | 'summary'` (models.py). */
export const MEMORY_SOURCES = ["manual", "filter_agent", "summary"] as const;
export type MemorySource = (typeof MEMORY_SOURCES)[number];

export const memoryEntrySchema = z.object({
  id: z.string(),
  cell_id: z.string(),
  kind: z.string(),
  title: z.string().nullable(),
  content: z.string(),
  tags: z.array(z.string()),
  source: z.string(),
  contains_pii: z.boolean(),
  created_at: z.string(),
  updated_at: z.string(),
});
export type MemoryEntry = z.infer<typeof memoryEntrySchema>;

export const roleMemoryEntrySchema = memoryEntrySchema.extend({
  agent_id: z.string(),
});
export type RoleMemoryEntry = z.infer<typeof roleMemoryEntrySchema>;

export const memorySearchHitSchema = z.object({
  entry: memoryEntrySchema,
  score: z.number(),
});
export type MemorySearchHit = z.infer<typeof memorySearchHitSchema>;

export const roleMemorySearchHitSchema = z.object({
  entry: roleMemoryEntrySchema,
  score: z.number(),
});
export type RoleMemorySearchHit = z.infer<typeof roleMemorySearchHitSchema>;

export interface AddMemoryPayload {
  kind?: CellMemoryKind;
  title?: string;
  content: string;
  tags?: string[];
  contains_pii?: boolean;
}

export interface AddRoleMemoryPayload {
  kind?: RoleMemoryKind;
  title?: string;
  content: string;
  tags?: string[];
  contains_pii?: boolean;
}

interface ListOpts {
  limit?: number;
  offset?: number;
}

function listQuery(opts: ListOpts): string {
  const params = new URLSearchParams();
  if (opts.limit !== undefined) params.set("limit", String(opts.limit));
  if (opts.offset !== undefined) params.set("offset", String(opts.offset));
  const qs = params.toString();
  return qs ? `?${qs}` : "";
}

function searchQuery(query: string, limit?: number): string {
  const params = new URLSearchParams({ q: query });
  if (limit !== undefined) params.set("limit", String(limit));
  return `?${params.toString()}`;
}

export const memoryApi = {
  // ── cell memory ──────────────────────────────────────────────────────── //

  list: (opts: ListOpts = {}) =>
    apiFetch(`/memory${listQuery(opts)}`, { schema: z.array(memoryEntrySchema) }),

  search: (query: string, limit?: number) =>
    apiFetch(`/memory/search${searchQuery(query, limit)}`, {
      schema: z.array(memorySearchHitSchema),
    }),

  add: (payload: AddMemoryPayload) =>
    apiFetch("/memory", { method: "POST", body: payload, schema: memoryEntrySchema }),

  remove: (entryId: string) => apiFetch<undefined>(`/memory/${entryId}`, { method: "DELETE" }),

  // ── role memory (per agent-instance) ────────────────────────────────── //

  listForAgent: (agentId: string, opts: ListOpts = {}) =>
    apiFetch(`/memory/agents/${agentId}${listQuery(opts)}`, {
      schema: z.array(roleMemoryEntrySchema),
    }),

  searchForAgent: (agentId: string, query: string, limit?: number) =>
    apiFetch(`/memory/agents/${agentId}/search${searchQuery(query, limit)}`, {
      schema: z.array(roleMemorySearchHitSchema),
    }),

  addForAgent: (agentId: string, payload: AddRoleMemoryPayload) =>
    apiFetch(`/memory/agents/${agentId}`, {
      method: "POST",
      body: payload,
      schema: roleMemoryEntrySchema,
    }),

  removeForAgent: (agentId: string, entryId: string) =>
    apiFetch<undefined>(`/memory/agents/${agentId}/${entryId}`, { method: "DELETE" }),
};
